(function(x){x.execute(function(){(function(){function o(){var e={pageStatusFlag:!1,checkMyReadyState:null,parse:function(b){var a=document,d=encodeURIComponent,j="",K=a.location.protocol+"//"+a.location.host,h={},x=!1,o=!1,l="",k=a.URL,p=1,f="",C="",q="",A="",m="",I="",g="",s="",L="",M="",r="",J="",N="",y="",B,D="",t="",O="",z="",E="",G="",Q="",c=0,n=[],H=0,w=e.getCookieValue("visitCount");w===""&&(w=0);try{e.checkMyReadyState=setInterval(function(){e.pageloadStatus();if(e.pageStatusFlag===!0){if(e.isDetailPage()){f=
a.getElementById("ASIN");typeof f!=="undefined"&&f!==null&&f.getAttribute("value")!==null&&(B=f.getAttribute("value"));f=a.getElementById("divsinglecolumnminwidth");if(typeof f!=="undefined"&&f!==null){g=f.getElementsByTagName("div");for(c=0;c<g.length;c++)if(typeof g[c]!=="undefined"&&g[c].getAttribute("id")===null&&g[c].className==="bucket"&&(s=g[c].getElementsByTagName("h2")[0],typeof s!=="undefined"&&s.innerHTML==="Look for similar items by category")){m=g[c].getElementsByTagName("a");C=m[m.length-
1];typeof m[0]!=="undefined"&&m[0]!==null&&m[0].innerHTML!==null&&(I=e.trimInend(m[0].innerHTML),I==="Electronics"?typeof m[1]!=="undefined"&&m[1]!==null&&m[1].innerHTML!==null&&(r=e.trimInend(m[1].innerHTML)):r=I);typeof C!=="undefined"&&C!==null&&C.innerHTML!==null&&(L=e.decodeAmpersand(e.trimInend(C.innerHTML)));A=g[c].getElementsByTagName("li");if(typeof A!=="undefined"&&A!==null)for(var i=0;i<A.length;i++){h["ecomm_ProductCatTree"+i]=A[i].textContent||A[i].innerText;var u=A[i].getElementsByTagName("a");
typeof u!=="undefined"&&u!==null&&u.length>0&&(h["browsernodeid"+i]=e.getQueryParamFromUrl("node",u[u.length-1].getAttribute("href")))}break}}if(r===""||r===null)if(f=a.getElementById("searchDropdownBox"),typeof f!=="undefined"&&f!==null)r=f.options[f.selectedIndex].text,r=e.trimInend(r);g=a.getElementById("handleBuy");if(typeof g!=="undefined"&&g!==null){f=g.getElementsByTagName("div");t=g.getElementsByTagName("span");q=g.getElementsByTagName("a");for(c=0;c<f.length;c++)if(typeof f[c]!=="undefined"&&
f[c].getAttribute("id")===null&&f[c].className==="buying"&&(s=f[c].getElementsByTagName("h1")[0],typeof s!=="undefined"&&s.className==="parseasinTitle")){y=f[c].innerHTML;y=e.trimInEndAndReplaceSpecialChars(y,"_");y=y.replace(/\s*/g,"");y.indexOf("_by_")!==-1&&(m=f[c].getElementsByTagName("a"),typeof m[0]!=="undefined"&&m[0]!==null&&m[0].innerHTML!==null&&(M=e.decodeAmpersand(e.trimInend(m[0].innerHTML))));break}for(c=0;c<t.length;c++)if(typeof t[c]!=="undefined"&&t[c].getAttribute("id")===null&&
t[c].className==="availGreen"){y=t[c].innerHTML;Q=e.trimInEndAndReplaceSpecialChars(y,"");break}for(c=0;c<q.length;c++)if(typeof q[c]!=="undefined"&&q[c].getAttribute("href")!==null&&q[c].getAttribute("href").indexOf("/gp/help/seller")>-1){h.ecomm_seller=q[c].textContent||q[c].innerText;break}}t=a.getElementById("productTitle");if(typeof t!=="undefined"&&t!==null)D=t.innerHTML,D=e.decodeAmpersand(e.trimInEndAndReplaceSpecialChars(D,""));O=k.indexOf("?")!==-1?k.substring(0,k.indexOf("?")):k;z=e.getImageSource("prodImage");
if(z===""||z===null)if(z=e.getImageSource("main-image"),z===""||z===null){f=a.getElementsByTagName("img");for(c=0;c<f.length;c++)if(typeof f[c]!=="undefined"&&f[c].className==="prod_image_selector"){z=f[c].getAttribute("src");break}}E=e.getPriceValue("listPriceValue");G=e.getPriceValue("actualPriceValue");if(E===null||E==="")E=G;r=e.decodeAmpersand(r);J=r+"_"+L;N=J+"_"+M;h.ecomm_pagetype="ProductDetail";h.ecomm_prodid=B;h.ecomm_price=G.replace(/,/g,"");h.ecomm_pcat=r;h.ecomm_pname=D;h.searchterm=
e.getParamFromQuery("field-keywords",a.location.search);w>5&&w<=10?p=2:w>10&&(p=3);l="e300";j=j+p+"&param="+l+"&pid="+B+"&catid="+d(d(r))+"&subcat1id="+d(d(J))+"&subcat2id="+d(d(N))+"&pname="+d(d(D))+"&lp="+d(d(O))+"&image="+d(d(z))+"&old="+E+"&new="+G+"&misc="+d(d(Q))}else if(k.indexOf("gp/huc/view.html")!==-1||k.indexOf("/gp/product/handle-buy-box/")!==-1){g=a.getElementById("hlb-page-container");if(typeof g!=="undefined"&&g!==null){f=g.getElementsByTagName("a");for(c=0;c<f.length;c++)if(typeof f[c]!==
"undefined"&&f[c].className.indexOf("hlb-item-link hlb-asin-")!==-1){B=f[c].className.split("hlb-item-link hlb-asin-")[1];break}}h.ecomm_prodid=B;h.ecomm_pagetype="ShoppingCart";l="e400";j=j+p+"&param="+l+"&pid1="+B+"&pid2=&pid3="}else if(k.indexOf("gp/cart")!==-1){g=a.getElementById("activeCartViewForm");if(typeof g!=="undefined"&&g!==null){f=g.getElementsByTagName("div");for(c=H=0;c<f.length;c++)typeof f[c]!=="undefined"&&f[c].className==="cart-item"&&f[c].getAttribute("asin")!==null&&(n.push(f[c].getAttribute("asin")),
h["pid"+H]=n[H],H++)}for(c=0;c<3;c++)typeof n[c]==="undefined"&&(n[c]="");l="e400";p=2;h.ecomm_pagetype="ShoppingCart";j=j+p+"&param="+l+"&pid1="+n[0]+"&pid2="+n[1]+"&pid3="+n[2]}else if(k.indexOf("/gp/buy/thankyou/")!==-1&&k.indexOf("viewId=ThankYouCart")!==-1){var i="",v=location.search.substring(1),u=function(a){return decodeURIComponent(a.replace(/\+/g," "))};if(v!==""&&v!==null&&v.indexOf("&")!==-1&&(v=v.split("&"),v.length>0))for(c=0;c<v.length;c++)if(v[c]!==""&&v[c]!==null){var F=v[c].split("=");
F.length>1&&(u(F[0])==="asins"?n.push(u(F[1])):u(F[0])==="orderId"&&(i=u(F[1])))}for(c=0;c<n.length;c++)h["pid"+c]=n[c];for(c=0;c<3;c++)typeof n[c]==="undefined"&&(n[c]="");h.ecomm_pagetype="CheckoutThankYou";h.orderid=i;l="e500";j=j+p+"&param="+l+"&pid1="+n[0]+"&pid2="+n[1]+"&pid3="+n[2]+"&orderid="+i}else if(k.indexOf("ap/signin")!==-1||k.indexOf("ap/register")!==-1||k.indexOf("buy/addressselect")!==-1||k.indexOf("buy/gift")!==-1||k.indexOf("buy/shipoptionselect")!==-1||k.indexOf("buy/pipeline")!==
-1||k.indexOf("buy/spc")!==-1)l="e400",p=3,j=j+p+"&param="+l;else if(k.indexOf("/b/ref")!==-1)l="e200",j=j+p+"&param="+l+"&catid=&subcat1id=&subcat2id=",h.ecomm_pagetype="Browse",h.ecomm_ProductCatTree=e.processBreadCrumb(),h.browsernodeid=e.getParamFromQuery("node",a.location.search);else if(k.indexOf("/s/ref")!==-1){if(l="e200",j=j+p+"&param="+l+"&catid=&subcat1id=&subcat2id=",h.ecomm_pagetype="Search",h.searchterm=e.getParamFromQuery("field-keywords",a.location.search),h.ecomm_ProductCatTree="",
g=a.getElementsByClassName("fstRow"),typeof g!=="undefined"&&g!==null&&g.length>0&&(s=g[0].getElementsByTagName("h3"),typeof s!=="undefined"&&s!==null&&s.length>0&&(q=s[0].getElementsByTagName("a"),typeof q!=="undefined"&&q!==null&&q.length>0&&(i=q[0].getAttribute("href"),typeof i!=="undefined"&&i!==null))))i=i.split("/ref")[0],i=i.split("/dp/"),i.length>1&&i[1].length===10&&(h.ecomm_prodid=i[1])}else{if(window.uept&&window.uept.pageType==="Gateway"||k===K||k===K+"/")h.ecomm_pagetype="Gateway",o=
!0;l="e100";j=j+p+"&param="+l}o=!0;w!==0?(w=parseInt(w,10)+1,e.setCookie("visitCount",w,30)):e.setCookie("visitCount",1,30);o&&!x&&(b.fireGooglePixel&&typeof h.ecomm_pagetype!=="undefined"&&(i=e.getGCustomParamString(h),e.callGoogleService(i)),b.fireVizuryPixel&&e.callVizuryService(j),x=!0)}},3E3,"Javascript")}catch(R){e.callVizuryService("&param=999")}},isDetailPage:function(){var b="",b=document.getElementById("addToCartSpan");if(typeof b!=="undefined"&&b!==null&&(b=document.getElementById("bb_atc_button"),
typeof b!=="undefined"&&b!==null&&b.getAttribute("alt")==="Add to Shopping Cart"))return!0;var b=document.URL,a="",a="";return b.indexOf("/ref")!==-1&&(a=b.split("/ref")[0],a=a.split("/"),a[a.length-1].length===10)?!0:e.isASINPresent(b,"dp/")?!0:e.isASINPresent(b,"gp/product/")?!0:!1},isASINPresent:function(b,a){var d="";b.indexOf(a)!==-1&&(d=b.split(a)[1]);d.indexOf("/")!==1&&(d=d.split("/")[0]);d.indexOf("?")!==1&&(d=d.split("?")[0]);return d.length===10?!0:!1},getGCustomParamString:function(b){var a=
function(a){return a<10?"0"+a:a},d=new Date;b.CURRENT_TIME=Date.prototype.toISOString?d.toISOString():d.getUTCFullYear()+"-"+a(d.getUTCMonth()+1)+"-"+a(d.getUTCDate())+"T"+a(d.getUTCHours())+":"+a(d.getUTCMinutes())+":"+a(d.getUTCSeconds())+"."+(d.getUTCMilliseconds()/1E3).toFixed(3).slice(2,5)+"Z";var a="",j;for(j in b)b.hasOwnProperty(j)&&(a=a+j+"="+b[j]+";");a=a+"SignedIn="+(e.isSignedIn()?"Y":"N");return encodeURIComponent(a)},processBreadCrumb:function(){var b="",a="",a=document.getElementById("refinements");
if(typeof a!=="undefined"&&a!==null&&(a=a.getElementsByClassName("categoryRefinementsSection"),typeof a!=="undefined"&&a!==null&&a.length>0&&(a=a[0],typeof a!=="undefined"&&a!==null&&(a=a.getElementsByTagName("li"),typeof a!=="undefined"&&a!==null&&a.length>0))))for(var d=0;d<a.length;d++)b=b.concat((a[d].textContent||a[d].innerText).trim()),d!=a.length-1&&(b=b.concat(" > "));return b},getQueryParamFromUrl:function(b,a){if(typeof a!=="undefined"&&a!==null&&a.indexOf("?")>-1){var d=a.substring(a.indexOf("?"));
return e.getParamFromQuery(b,d)}return""},getParamFromQuery:function(b,a){if(typeof a!=="undefined"&&a!==null&&a.length>0)for(var d="",e=a.substring(1).split("&"),o=0;o<e.length;o++)if(d=e[o].split("="),d.length>0&&d[0]===b)return d[1];return""},isSignedIn:function(){var b=document.getElementById("nav-your-account");if(typeof b!=="undefined"&&b!==null&&(b=b.getAttribute("href"),typeof b!=="undefined"&&b!==null)){if(b.indexOf("/redirect.html")!==-1){var a=e.getQueryParamFromUrl("location",b);a.length>
0&&(b=decodeURIComponent(a))}if(b.indexOf("/ap/signin")===-1)return!0}return!1},pageloadStatus:function(){document.readyState==="interactive"||document.readyState==="complete"?(e.pageStatusFlag=!0,clearInterval(e.checkMyReadyState)):e.pageStatusFlag=!1},setCookie:function(b,a,d){if(d!==-1){var e=new Date;e.setDate(e.getDate()+d);a=encodeURIComponent(a)+(d===null?"":"; expires="+e.toUTCString())+"; path=/; domain=.amazon.in"}document.cookie=b+"="+a},getCookieValue:function(b){var a=document.cookie;
if(a.length>0){var d=a.indexOf(b+"=");if(d!==-1){d=d+b.length+1;b=a.indexOf(";",d);if(b===-1)b=a.length;a=decodeURIComponent(a.substring(d,b));if(a!==void 0&&a!==null)return a}}return""},getImageSource:function(b){var a="",d="";typeof b!=="undefined"&&b!==""&&b!==null&&(d=document.getElementById(b),typeof d!=="undefined"&&d!==null&&d.getAttribute("src")!==null&&(a=d.getAttribute("src")));return a},getPriceValue:function(b){var a="",b=document.getElementById(b);if(typeof b!=="undefined"&&b!==null)a=
b.innerHTML,a=e.trimInEndAndReplaceSpecialChars(a).replace(/[^0-9.,]/g,""),a.charAt(0)==="."&&(a=a.substr(1));return a},trimInend:function(b){return typeof b!=="undefined"&&b!==""&&b!==null?(b=b.replace(/(^\s*)|(\s*$)/gi,""),b=b.replace(/[ ]{2,}/gi," "),b=b.replace(/\n /,"\n")):""},trimInEndAndReplaceSpecialChars:function(b,a){return e.trimInend(b.replace(/(<([^>]+)>)/ig,a))},decodeAmpersand:function(b){return b.replace(/&amp;/g,"&")},callVizuryService:function(b){var a=("https:"===document.location.protocol?
"https://ssl":"http://www")+".vizury.com/analyze/analyze.php",d=document.createElement("iframe");d.src=a+"?account_id=VIZVRM1256&section=1&level="+b;d.scrolling="no";d.width=1;d.height=1;d.marginheight=0;d.marginwidth=0;d.frameborder=0;d.style.display="block";b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(d,b)},callGoogleService:function(b){(new Image).src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/984527532/?value=0&label=r_58CJXm0gIQw9iz3gM&guid=ON&script=0&data="+
b}};return e}if(window.amznJQ)window.RetargetingPixel=o(),amznJQ.declareAvailable("inRetargeting");window.P&&x.register("inRetargeting",o)})()})})(function(){var x=window.AmazonUIPageJS||P,o=x.attributeErrors;return o?o("INRetargetingAsset"):x}());